name: Generate and Commit Layout Image

on:
  push:
    branches:
      - main

jobs:
  generate-image:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout qmk_firmware
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          path: qmk_firmware

      - name: Install qmk and keymap-drawer
        run: pip install qmk keymap-drawer

      - name: Generate layout image
        run: |
          qmk config user.qmk_home=$GITHUB_WORKSPACE/qmk_firmware user.overlay_dir=$GITHUB_WORKSPACE
          qmk c2json -kb splitkb/aurora/sweep/rev1 -km samiser -o /tmp/samiser.json keyboards/splitkb/aurora/sweep/keymaps/samiser/keymap.c
          keymap parse -q /tmp/samiser.json > /tmp/samiser.yaml
          keymap draw /tmp/samiser.yaml > splitkb_aurora_sweep.svg

      - name: Commit and push generated layout image
        if: ${{ success() }}
        run: |
          if [[ $(git status --porcelain splitkb_aurora_sweep.svg) ]]; then
            echo "Image changed, committing..."
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add splitkb_aurora_sweep.svg
            git commit -m "Auto-update generated image"
            git push
          else
            echo "No changes to commit."
          fi
